---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
    exclude_fingerprints:
      - a455ac0cedfef808dec73ada52eeea77
  fixme:
    enabled: true
  radon:
    enabled: true
    exclude_fingerprints:
      - 8e7f62a46a532f5debebcd18faf7427f
      - 44d851aed969453a83a046662b0c0bfe
ratings:
  paths:
  - "**.py"
exclude_paths: []
