---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
    exclude_fingerprints:
      - a455ac0cedfef808dec73ada52eeea77
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths: []
