language: python
matrix:
  include:
    - python: 2.6
      env:
      - TOXENV=py26
    - python: 2.7
      env:
      - TOXENV=py27
    - python: 3.3
      env:
      - TOXENV=py33
    - python: 3.4
      env:
      - TOXENV=py34
    - python: 3.5
      env:
      - TOXENV=py35
    - python: pypy
      env:
      - TOXENV=pypy
    - python: pypy3
      env:
      - TOXENV=pypy3
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
deploy:
  provider: pypi
  user: themattrix
  distributions: sdist bdist_wheel
  on:
    condition: $TOXENV == py27
    tags: true
    all_branches: true
    repo: themattrix/python-temporary
  password:
    secure: UbHjph8cfcRUmZM9Z+o1Bkc3WjU1vhiPN9ipwfVZXmT6P5TXjMioSGnxD9r56i3lwtcqee5e4AOEx6uHuHSSvodkskLrMOcZVzXe5xcmE+90R7uHgDVapIuoeQIgoqfB5Tx1QaGsw2bpUe7azZLQpVCtZZpU1IoelFq/CXNbR3Y=
